# Creates an AMI using ec2 modules from Ansible and the connects to the AMI to configure it with all the necessary apps
---
# creates the AMI, hosts and connection forced to local to use the EC2 modules
- name: Launch instance
  local_action: ec2 key_name=${keypair} group=${sec_group_name} instance_type=${instance_type} image=${image} wait=yes count=1 region=${ec2_region}
  register: ec2
    
- name: Add new instances to host group
  local_action: add_host name=${item.public_dns_name} groups=deploy
  with_items: ${ec2.instances}

- name: Connect via SSH
  local_action: wait_for host=${item.public_dns_name} port=22
  with_items: ${ec2.instances}
 
- name: Wait before starting configuration (to avoid startup issues)
  pause: seconds=20

